### PR TITLE
Update golang.org/x/sys commit hash to 0f9fa26a

### PR DESCRIPTION
**Pull request by cookieY**
Fixed go 1.17  panic

fatal error: unexpected signal during runtime execution

Related links https://github.com/golang/go/issues/47279

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by shoenseiwaso** [comment]
@cookieY thanks for the fix and @mattn thanks for merging and for the library! Would you mind pushing a new release so downstream dependencies can also update?

**Comment by mattn** [comment]
Tagged v0.0.14

**Comment by shoenseiwaso** [comment]
Thanks @mattn, much appreciated!

**Comment by dolmen** [comment]
golang.org/x/sys has been upgraded again in #82.

@mattn This issue can be closed.

**Pull request merged**
