### PR TITLE
fix build when GOOS=js

### LINKED ISSUE #26: build failed when GOOS=js
I'm currently working on a tool that allow us to use regular http handlers on nodejs side

this package is a dependency for most of the http muxers available in the go world
is it possible to add build constrain so it can compile when GOOS=js and GOARCH=wasm ?

thank you

### PR DESCRIPTION
**Pull request by thesyncim**
fixes #26

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, This is my wrong that UNIX doesn't have IsCygwinTerminal too. So l want to make go-isatty have always IsTerminal/IsCygwinTerminal both even if it's not Windows. Could you please merge isatty_appengine.go ?

**Comment by thesyncim** [comment]
is this ok for you? or do you want to me to simplify a bit more the build constrains?
thank you

**Comment by mattn** [comment]
Thanks. I want to remove isatty_others.go

```diff
diff --git a/isatty_bsd.go b/isatty_bsd.go
index 42f2514..07e9303 100644
--- a/isatty_bsd.go
+++ b/isatty_bsd.go
@@ -16,3 +16,9 @@ func IsTerminal(fd uintptr) bool {
 	_, _, err := syscall.Syscall6(syscall.SYS_IOCTL, fd, ioctlReadTermios, uintptr(unsafe.Pointer(&termios)), 0, 0, 0)
 	return err == 0
 }
+
+// IsCygwinTerminal return true if the file descriptor is a cygwin or msys2
+// terminal. This is also always false on this environment.
+func IsCygwinTerminal(fd uintptr) bool {
+	return false
+}
diff --git a/isatty_linux.go b/isatty_linux.go
index 7384cf9..1f40026 100644
--- a/isatty_linux.go
+++ b/isatty_linux.go
@@ -16,3 +16,9 @@ func IsTerminal(fd uintptr) bool {
 	_, _, err := syscall.Syscall6(syscall.SYS_IOCTL, fd, ioctlReadTermios, uintptr(unsafe.Pointer(&termios)), 0, 0, 0)
 	return err == 0
 }
+
+// IsCygwinTerminal return true if the file descriptor is a cygwin or msys2
+// terminal. This is also always false on this environment.
+func IsCygwinTerminal(fd uintptr) bool {
+	return false
+}
diff --git a/isatty_linux_ppc64x.go b/isatty_linux_ppc64x.go
index 44e5d21..bb7d3c4 100644
--- a/isatty_linux_ppc64x.go
+++ b/isatty_linux_ppc64x.go
@@ -17,3 +17,9 @@ func IsTerminal(fd uintptr) bool {
 	_, _, err := syscall.Syscall6(syscall.SYS_IOCTL, fd, ioctlReadTermios, uintptr(unsafe.Pointer(&termios)), 0, 0, 0)
 	return err == 0
 }
+
+// IsCygwinTerminal return true if the file descriptor is a cygwin or msys2
+// terminal. This is also always false on this environment.
+func IsCygwinTerminal(fd uintptr) bool {
+	return false
+}
diff --git a/isatty_solaris.go b/isatty_solaris.go
index 1f0c6bf..bdd5c79 100644
--- a/isatty_solaris.go
+++ b/isatty_solaris.go
@@ -14,3 +14,9 @@ func IsTerminal(fd uintptr) bool {
 	err := unix.IoctlSetTermio(int(fd), unix.TCGETA, &termio)
 	return err == nil
 }
+
+// IsCygwinTerminal return true if the file descriptor is a cygwin or msys2
+// terminal. This is also always false on this environment.
+func IsCygwinTerminal(fd uintptr) bool {
+	return false
+}
```

**Comment by thesyncim** [comment]
should we rename isatty_appengine to isatty_others?

**Comment by mattn** [comment]
good catch. please do.

**Comment by thesyncim** [comment]
done!
thanks for your time

**Comment by mattn** [comment]
Thank you

**Pull request merged**
