### PR TITLE
Add IsCygwinTerminal to Android build

### LINKED ISSUE #31: Missing method
After you have added separate source for android builds, gin is failing because cannot find `IsCygwinTerminal` for android build.
```
../../gin-gonic/gin/logger.go:201:67: undefined: isatty.IsCygwinTerminal
```

### PR DESCRIPTION
**Pull request by rasa**
Fixes #31

### CODE REVIEW

**Comment by mattn** [comment]
Oh, sorry. I'd miss your PR. I noticed just now. Sorry...

**Comment by mattn** [comment]
Oh, sorry. I'd miss your PR. I noticed just now. Sorry...

**Comment by mattn** [comment]
Closed by #33

**Comment by rasa** [comment]
No worries. Thanks!

**Pull request closed without merging**
