### PR TITLE
Update isatty_others.go

### PR DESCRIPTION
**Pull request by aeppert**
Fix building for Darwin targets.

### CODE REVIEW

**Comment by mattn** [comment]
I don't make sure because I don't have macOS. isatty_bsd.go should do?

**Comment by aeppert** [comment]
The issue, either way, IsCygwinTerminal, needs to return false and exist as
a symbol otherwise compilation will fail otherwise if someone is testing
for it.

Aaron

**Comment by mattn** [comment]
Ah, make sense.

**Comment by mattn** [comment]
Thank you

**Comment by mattn** [comment]
I don't have macOS but seems to be able to build with macOS in latest code.

**Comment by mattn** [comment]
@aeppert see https://travis-ci.org/mattn/go-isatty/jobs/298368090

**Pull request merged**
